# Generated by kibo from gei. Do not edit by hand.
# Templates: kibo-template-viper 2.0.0 (MIT), Template Model 2.
# Runtime: this file imports `dsviper` 1.2.x,
# distributed under LicenseRef-DigitalSubstrate-Commercial-1.2.
# Commercial use requires a Commercial Licence from Digital Substrate.
# Generated from /Volumes/DigitalSubstrate/kibo-2/dsviper-ge-qml/GE.dsm.json by kibo-2.0.0.jar

"""Graph — ce que cette unité expose.

L'INITIALISATEUR NE PORTE QUE DES NOMS. Les classes vivent dans `data`, les attachments
dans `attachments`, et l'un des deux n'est pas importé ici : un initialisateur qui
importerait `attachments` ferait de l'import d'une unité l'import de tout ce qu'elle
atteint, et deux unités qui se référencent par un attachment deviendraient un cycle.

    from gei.graph import attachments
"""

from .data import *