# Generated by kibo from gei. Do not edit by hand.
# Templates: kibo-template-viper 2.0.0 (MIT), Template Model 2.
# Runtime: this file imports `dsviper` 1.2.x,
# distributed under LicenseRef-DigitalSubstrate-Commercial-1.2.
# Commercial use requires a Commercial Licence from Digital Substrate.
# Generated from /Volumes/DigitalSubstrate/kibo-2/dsviper-ge-qml/GE.dsm.json by kibo-2.0.0.jar

"""Graph — les types que ce namespace déclare."""

from __future__ import annotations

import enum
import functools
import typing

import dsviper

from .. import definitions
from .._codegen import (NEUF as _NEUF, AnyConceptKey, Mapping, Ordered, Proxy, Sequence,
                        is_known, register, unwrap, wrap)

# ── l'identité de cette unité dans le modèle ──
#
# LE MÊME ARTEFACT QU'EN C++, POUR LA MÊME RAISON : plusieurs couches en ont besoin et ce
# n'est pas de la sérialisation. Il tient ici en une constante par type, parce qu'il n'y a
# pas de tag à porter — l'appelant nomme la classe.

EDGE: dsviper.ValueUUId = dsviper.ValueUUId.create("4d5c7e70-1262-eac1-f8c1-2eb35df4c5cf")
GRAPH: dsviper.ValueUUId = dsviper.ValueUUId.create("0785ad82-048d-7992-5680-edd838ee5ad6")
VERTEX: dsviper.ValueUUId = dsviper.ValueUUId.create("2f11dc82-c440-640f-b684-210936c58f86")
COLOR: dsviper.ValueUUId = dsviper.ValueUUId.create("469d48ae-0e43-0a83-54e6-76eb6ca48d1b")
EDGE_TOPOLOGY: dsviper.ValueUUId = dsviper.ValueUUId.create("00c3d01c-4814-2585-d21c-05f482f2ca77")
GRAPH_DESCRIPTION: dsviper.ValueUUId = dsviper.ValueUUId.create("26b02bf2-78f3-75ff-9fc9-6be36ee21dc8")
GRAPH_SELECTION: dsviper.ValueUUId = dsviper.ValueUUId.create("6285942c-da2d-82bb-9b4c-8c353ad3dad3")
GRAPH_TOPOLOGY: dsviper.ValueUUId = dsviper.ValueUUId.create("8908c86a-01f0-60ed-f3e9-204a52ccef05")
POSITION: dsviper.ValueUUId = dsviper.ValueUUId.create("576fbb64-0742-db36-422b-5a35ff1fa25f")
RECTANGLE: dsviper.ValueUUId = dsviper.ValueUUId.create("dce3db08-b7f7-946c-f02a-32898c72f40d")
VERTEX_2D_ATTRIBUTES: dsviper.ValueUUId = dsviper.ValueUUId.create("d233a482-09ff-5363-8316-97ae4ba4ab5e")
VERTEX_VISUAL_ATTRIBUTES: dsviper.ValueUUId = dsviper.ValueUUId.create("a530433b-d52c-b261-30aa-aa4b3a623fd8")

class EdgeKey(Proxy):
    """Une poignée sur une instance de Graph::Edge, pas la chose elle-même.

    An edge in a graph.
    """

    __slots__ = ()

    @classmethod
    @functools.cache
    def concept(cls):
        """Le descripteur, résolu une fois."""
        return definitions().check_concept(EDGE)

    @classmethod
    @functools.cache
    def type(cls) -> dsviper.Type:
        """Le descripteur du type de la clé.

        `classmethod` et non fonction libre : en C++ il fallait `type(tag<T>{})` pour que la
        recherche par argument trouve l'unité de T. Python n'a pas cette recherche et n'en a
        pas besoin — l'appelant écrit déjà le nom de la classe.
        """
        return dsviper.TypeKey(cls.concept())

    def __init__(self, identifier: typing.Any = _NEUF):
        # `None` EXPLICITE N'EST PAS L'ABSENCE D'ARGUMENT. `EdgeKey()` demande une clé
        # neuve ; `EdgeKey(None)` passe quelque chose, et ce quelque chose n'est pas un
        # identifiant. Un témoin distingue les deux là où `None` ne le peut pas.
        if identifier is _NEUF:
            identifier = None
        elif identifier is None:
            raise TypeError("None n'est pas un identifiant d'instance")

        if isinstance(identifier, dsviper.ValueKey):
            if not identifier.is_member(self.concept()):
                raise TypeError("cette valeur n'est pas un Graph::EdgeKey")
            super().__init__(identifier)
        elif identifier is None or isinstance(identifier, (dsviper.ValueUUId, str)):
            super().__init__(dsviper.ValueKey.create(self.concept(), identifier))
        else:
            # UN IDENTIFIANT EST UNE CHAÎNE OU UN UUId, ET RIEN D'AUTRE. Laisser passer un
            # entier ou une liste ferait lever le runtime -- ce qui est juste, mais par une
            # erreur qui parle de décodage plutôt que du type qu'on lui a donné.
            raise TypeError(f"{identifier!r} n'est pas un identifiant d'instance")

    @classmethod
    def decode(cls, blob, **kwargs) -> EdgeKey:
        """Relire depuis des octets : la classe connaît son type."""
        return cls(dsviper.ValueKey.cast(
            dsviper.Value.decode(blob, cls.type(), definitions(), **kwargs)))

    @classmethod
    def create(cls) -> EdgeKey:
        """Une clé sur une instance neuve. L'instance n'existe pas tant que rien ne l'écrit."""
        return cls(dsviper.ValueUUId.create())

    def instance_id(self) -> dsviper.ValueUUId:
        return self._value.instance_id()

    def runtime_id(self) -> dsviper.ValueUUId:
        return self._value.type_concept().runtime_id()

    def is_valid(self) -> bool:
        return self._value.instance_id().is_valid()

    # La clé, vue sans son type.
    def to_any_concept_key(self) -> AnyConceptKey:
        return AnyConceptKey(self._value.to_any_concept_key())

    @classmethod
    def from_any_concept_key(cls, key) -> EdgeKey | None:
        """La clé non typée, retypée — ou `None` si elle ne désigne pas ce concept.

        LE CHEMIN DE RETOUR, ET IL PEUT ÉCHOUER. Élargir ne perd rien ; rétrécir pose une
        question dont la réponse est dans l'identifiant que la valeur porte.
        """
        value = key._value if isinstance(key, Proxy) else key
        return cls(value) if value.type_concept().runtime_id() == EDGE else None

    def description(self) -> str:
        """L'instance et son type, dits comme le modèle les nomme.

        `Value.description()` du runtime rend `key<Demo::ConceptA>` : la forme du *type*, qui
        est juste et n'est pas ce qu'un lecteur cherche. Ici c'est le nom de la classe qu'il
        tient, et `__repr__` rend la même chose — deux façons de demander, une réponse.
        """
        return f"{self._value.instance_id().encoded()}:Graph::EdgeKey"

    def is_known(self) -> bool:
        return is_known(self._value)

    def __repr__(self) -> str:
        return self.description()



class GraphKey(Proxy):
    """Une poignée sur une instance de Graph::Graph, pas la chose elle-même.

    A graph.
    """

    __slots__ = ()

    @classmethod
    @functools.cache
    def concept(cls):
        """Le descripteur, résolu une fois."""
        return definitions().check_concept(GRAPH)

    @classmethod
    @functools.cache
    def type(cls) -> dsviper.Type:
        """Le descripteur du type de la clé.

        `classmethod` et non fonction libre : en C++ il fallait `type(tag<T>{})` pour que la
        recherche par argument trouve l'unité de T. Python n'a pas cette recherche et n'en a
        pas besoin — l'appelant écrit déjà le nom de la classe.
        """
        return dsviper.TypeKey(cls.concept())

    def __init__(self, identifier: typing.Any = _NEUF):
        # `None` EXPLICITE N'EST PAS L'ABSENCE D'ARGUMENT. `GraphKey()` demande une clé
        # neuve ; `GraphKey(None)` passe quelque chose, et ce quelque chose n'est pas un
        # identifiant. Un témoin distingue les deux là où `None` ne le peut pas.
        if identifier is _NEUF:
            identifier = None
        elif identifier is None:
            raise TypeError("None n'est pas un identifiant d'instance")

        if isinstance(identifier, dsviper.ValueKey):
            if not identifier.is_member(self.concept()):
                raise TypeError("cette valeur n'est pas un Graph::GraphKey")
            super().__init__(identifier)
        elif identifier is None or isinstance(identifier, (dsviper.ValueUUId, str)):
            super().__init__(dsviper.ValueKey.create(self.concept(), identifier))
        else:
            # UN IDENTIFIANT EST UNE CHAÎNE OU UN UUId, ET RIEN D'AUTRE. Laisser passer un
            # entier ou une liste ferait lever le runtime -- ce qui est juste, mais par une
            # erreur qui parle de décodage plutôt que du type qu'on lui a donné.
            raise TypeError(f"{identifier!r} n'est pas un identifiant d'instance")

    @classmethod
    def decode(cls, blob, **kwargs) -> GraphKey:
        """Relire depuis des octets : la classe connaît son type."""
        return cls(dsviper.ValueKey.cast(
            dsviper.Value.decode(blob, cls.type(), definitions(), **kwargs)))

    @classmethod
    def create(cls) -> GraphKey:
        """Une clé sur une instance neuve. L'instance n'existe pas tant que rien ne l'écrit."""
        return cls(dsviper.ValueUUId.create())

    def instance_id(self) -> dsviper.ValueUUId:
        return self._value.instance_id()

    def runtime_id(self) -> dsviper.ValueUUId:
        return self._value.type_concept().runtime_id()

    def is_valid(self) -> bool:
        return self._value.instance_id().is_valid()

    # La clé, vue sans son type.
    def to_any_concept_key(self) -> AnyConceptKey:
        return AnyConceptKey(self._value.to_any_concept_key())

    @classmethod
    def from_any_concept_key(cls, key) -> GraphKey | None:
        """La clé non typée, retypée — ou `None` si elle ne désigne pas ce concept.

        LE CHEMIN DE RETOUR, ET IL PEUT ÉCHOUER. Élargir ne perd rien ; rétrécir pose une
        question dont la réponse est dans l'identifiant que la valeur porte.
        """
        value = key._value if isinstance(key, Proxy) else key
        return cls(value) if value.type_concept().runtime_id() == GRAPH else None

    def description(self) -> str:
        """L'instance et son type, dits comme le modèle les nomme.

        `Value.description()` du runtime rend `key<Demo::ConceptA>` : la forme du *type*, qui
        est juste et n'est pas ce qu'un lecteur cherche. Ici c'est le nom de la classe qu'il
        tient, et `__repr__` rend la même chose — deux façons de demander, une réponse.
        """
        return f"{self._value.instance_id().encoded()}:Graph::GraphKey"

    def is_known(self) -> bool:
        return is_known(self._value)

    def __repr__(self) -> str:
        return self.description()



class VertexKey(Proxy):
    """Une poignée sur une instance de Graph::Vertex, pas la chose elle-même.

    A vertex in a graph.
    """

    __slots__ = ()

    @classmethod
    @functools.cache
    def concept(cls):
        """Le descripteur, résolu une fois."""
        return definitions().check_concept(VERTEX)

    @classmethod
    @functools.cache
    def type(cls) -> dsviper.Type:
        """Le descripteur du type de la clé.

        `classmethod` et non fonction libre : en C++ il fallait `type(tag<T>{})` pour que la
        recherche par argument trouve l'unité de T. Python n'a pas cette recherche et n'en a
        pas besoin — l'appelant écrit déjà le nom de la classe.
        """
        return dsviper.TypeKey(cls.concept())

    def __init__(self, identifier: typing.Any = _NEUF):
        # `None` EXPLICITE N'EST PAS L'ABSENCE D'ARGUMENT. `VertexKey()` demande une clé
        # neuve ; `VertexKey(None)` passe quelque chose, et ce quelque chose n'est pas un
        # identifiant. Un témoin distingue les deux là où `None` ne le peut pas.
        if identifier is _NEUF:
            identifier = None
        elif identifier is None:
            raise TypeError("None n'est pas un identifiant d'instance")

        if isinstance(identifier, dsviper.ValueKey):
            if not identifier.is_member(self.concept()):
                raise TypeError("cette valeur n'est pas un Graph::VertexKey")
            super().__init__(identifier)
        elif identifier is None or isinstance(identifier, (dsviper.ValueUUId, str)):
            super().__init__(dsviper.ValueKey.create(self.concept(), identifier))
        else:
            # UN IDENTIFIANT EST UNE CHAÎNE OU UN UUId, ET RIEN D'AUTRE. Laisser passer un
            # entier ou une liste ferait lever le runtime -- ce qui est juste, mais par une
            # erreur qui parle de décodage plutôt que du type qu'on lui a donné.
            raise TypeError(f"{identifier!r} n'est pas un identifiant d'instance")

    @classmethod
    def decode(cls, blob, **kwargs) -> VertexKey:
        """Relire depuis des octets : la classe connaît son type."""
        return cls(dsviper.ValueKey.cast(
            dsviper.Value.decode(blob, cls.type(), definitions(), **kwargs)))

    @classmethod
    def create(cls) -> VertexKey:
        """Une clé sur une instance neuve. L'instance n'existe pas tant que rien ne l'écrit."""
        return cls(dsviper.ValueUUId.create())

    def instance_id(self) -> dsviper.ValueUUId:
        return self._value.instance_id()

    def runtime_id(self) -> dsviper.ValueUUId:
        return self._value.type_concept().runtime_id()

    def is_valid(self) -> bool:
        return self._value.instance_id().is_valid()

    # La clé, vue sans son type.
    def to_any_concept_key(self) -> AnyConceptKey:
        return AnyConceptKey(self._value.to_any_concept_key())

    @classmethod
    def from_any_concept_key(cls, key) -> VertexKey | None:
        """La clé non typée, retypée — ou `None` si elle ne désigne pas ce concept.

        LE CHEMIN DE RETOUR, ET IL PEUT ÉCHOUER. Élargir ne perd rien ; rétrécir pose une
        question dont la réponse est dans l'identifiant que la valeur porte.
        """
        value = key._value if isinstance(key, Proxy) else key
        return cls(value) if value.type_concept().runtime_id() == VERTEX else None

    def description(self) -> str:
        """L'instance et son type, dits comme le modèle les nomme.

        `Value.description()` du runtime rend `key<Demo::ConceptA>` : la forme du *type*, qui
        est juste et n'est pas ce qu'un lecteur cherche. Ici c'est le nom de la classe qu'il
        tient, et `__repr__` rend la même chose — deux façons de demander, une réponse.
        """
        return f"{self._value.instance_id().encoded()}:Graph::VertexKey"

    def is_known(self) -> bool:
        return is_known(self._value)

    def __repr__(self) -> str:
        return self.description()


class Color(Proxy):
    """Graph::Color.

    An RGB Color.
    """

    __slots__ = ()

    @classmethod
    @functools.cache
    def type(cls) -> dsviper.TypeStructure:
        return definitions().check_structure(COLOR)

    @classmethod
    def decode(cls, blob, **kwargs) -> Color:
        """Relire depuis des octets : la classe connaît son type, donc elle peut le demander."""
        return cls(dsviper.ValueStructure.cast(
            dsviper.Value.decode(blob, cls.type(), definitions(), **kwargs)))

    def __init__(self, value: dsviper.ValueStructure | dict | None = None, /, **fields):
        if value is None:
            value = dsviper.ValueStructure(self.type())
        elif isinstance(value, dict):
            value = dsviper.ValueStructure(self.type(), value)
        elif value.type() != self.type():
            raise TypeError("cette valeur n'est pas un Graph::Color")
        super().__init__(value)

        for name, field in fields.items():
            setattr(self, name, field)

    @property
    def red(self) -> float:
        return self._value.at("red")

    @red.setter
    def red(self, value: float) -> None:
        self._value.set("red", value)

    @property
    def green(self) -> float:
        return self._value.at("green")

    @green.setter
    def green(self, value: float) -> None:
        self._value.set("green", value)

    @property
    def blue(self) -> float:
        return self._value.at("blue")

    @blue.setter
    def blue(self, value: float) -> None:
        self._value.set("blue", value)

    def __repr__(self) -> str:
        return f"Graph::Color(red={self.red}, green={self.green}, blue={self.blue})"


class EdgeTopology(Proxy):
    """Graph::EdgeTopology.

    An edge in the graph topology.
    """

    __slots__ = ()

    @classmethod
    @functools.cache
    def type(cls) -> dsviper.TypeStructure:
        return definitions().check_structure(EDGE_TOPOLOGY)

    @classmethod
    def decode(cls, blob, **kwargs) -> EdgeTopology:
        """Relire depuis des octets : la classe connaît son type, donc elle peut le demander."""
        return cls(dsviper.ValueStructure.cast(
            dsviper.Value.decode(blob, cls.type(), definitions(), **kwargs)))

    def __init__(self, value: dsviper.ValueStructure | dict | None = None, /, **fields):
        if value is None:
            value = dsviper.ValueStructure(self.type())
        elif isinstance(value, dict):
            value = dsviper.ValueStructure(self.type(), value)
        elif value.type() != self.type():
            raise TypeError("cette valeur n'est pas un Graph::EdgeTopology")
        super().__init__(value)

        for name, field in fields.items():
            setattr(self, name, field)

    @property
    def va_key(self) -> VertexKey:
        return wrap(self._value.at("vaKey", encoded=False))

    @va_key.setter
    def va_key(self, value: VertexKey) -> None:
        self._value.set("vaKey", unwrap(value))

    @property
    def vb_key(self) -> VertexKey:
        return wrap(self._value.at("vbKey", encoded=False))

    @vb_key.setter
    def vb_key(self, value: VertexKey) -> None:
        self._value.set("vbKey", unwrap(value))

    def __repr__(self) -> str:
        return f"Graph::EdgeTopology(va_key={self.va_key}, vb_key={self.vb_key})"


class GraphDescription(Proxy):
    """Graph::GraphDescription.

    The descriptive information's.
    """

    __slots__ = ()

    @classmethod
    @functools.cache
    def type(cls) -> dsviper.TypeStructure:
        return definitions().check_structure(GRAPH_DESCRIPTION)

    @classmethod
    def decode(cls, blob, **kwargs) -> GraphDescription:
        """Relire depuis des octets : la classe connaît son type, donc elle peut le demander."""
        return cls(dsviper.ValueStructure.cast(
            dsviper.Value.decode(blob, cls.type(), definitions(), **kwargs)))

    def __init__(self, value: dsviper.ValueStructure | dict | None = None, /, **fields):
        if value is None:
            value = dsviper.ValueStructure(self.type())
        elif isinstance(value, dict):
            value = dsviper.ValueStructure(self.type(), value)
        elif value.type() != self.type():
            raise TypeError("cette valeur n'est pas un Graph::GraphDescription")
        super().__init__(value)

        for name, field in fields.items():
            setattr(self, name, field)

    @property
    def name(self) -> str:
        return self._value.at("name")

    @name.setter
    def name(self, value: str) -> None:
        self._value.set("name", value)

    @property
    def author(self) -> str:
        return self._value.at("author")

    @author.setter
    def author(self, value: str) -> None:
        self._value.set("author", value)

    @property
    def create_date(self) -> str:
        return self._value.at("createDate")

    @create_date.setter
    def create_date(self, value: str) -> None:
        self._value.set("createDate", value)

    def __repr__(self) -> str:
        return f"Graph::GraphDescription(name={self.name}, author={self.author}, create_date={self.create_date})"


class GraphSelection(Proxy):
    """Graph::GraphSelection.

    The selected vertices and edges.
    """

    __slots__ = ()

    @classmethod
    @functools.cache
    def type(cls) -> dsviper.TypeStructure:
        return definitions().check_structure(GRAPH_SELECTION)

    @classmethod
    def decode(cls, blob, **kwargs) -> GraphSelection:
        """Relire depuis des octets : la classe connaît son type, donc elle peut le demander."""
        return cls(dsviper.ValueStructure.cast(
            dsviper.Value.decode(blob, cls.type(), definitions(), **kwargs)))

    def __init__(self, value: dsviper.ValueStructure | dict | None = None, /, **fields):
        if value is None:
            value = dsviper.ValueStructure(self.type())
        elif isinstance(value, dict):
            value = dsviper.ValueStructure(self.type(), value)
        elif value.type() != self.type():
            raise TypeError("cette valeur n'est pas un Graph::GraphSelection")
        super().__init__(value)

        for name, field in fields.items():
            setattr(self, name, field)

    @property
    def vertex_keys(self) -> Sequence[VertexKey]:
        return wrap(self._value.at("vertexKeys", encoded=False))

    @vertex_keys.setter
    def vertex_keys(self, value: Sequence[VertexKey]) -> None:
        self._value.set("vertexKeys", unwrap(value))

    @property
    def edge_keys(self) -> Sequence[EdgeKey]:
        return wrap(self._value.at("edgeKeys", encoded=False))

    @edge_keys.setter
    def edge_keys(self, value: Sequence[EdgeKey]) -> None:
        self._value.set("edgeKeys", unwrap(value))

    def __repr__(self) -> str:
        return f"Graph::GraphSelection(vertex_keys={self.vertex_keys}, edge_keys={self.edge_keys})"


class GraphTopology(Proxy):
    """Graph::GraphTopology.

    The vertices and edges of the graph topology.
    """

    __slots__ = ()

    @classmethod
    @functools.cache
    def type(cls) -> dsviper.TypeStructure:
        return definitions().check_structure(GRAPH_TOPOLOGY)

    @classmethod
    def decode(cls, blob, **kwargs) -> GraphTopology:
        """Relire depuis des octets : la classe connaît son type, donc elle peut le demander."""
        return cls(dsviper.ValueStructure.cast(
            dsviper.Value.decode(blob, cls.type(), definitions(), **kwargs)))

    def __init__(self, value: dsviper.ValueStructure | dict | None = None, /, **fields):
        if value is None:
            value = dsviper.ValueStructure(self.type())
        elif isinstance(value, dict):
            value = dsviper.ValueStructure(self.type(), value)
        elif value.type() != self.type():
            raise TypeError("cette valeur n'est pas un Graph::GraphTopology")
        super().__init__(value)

        for name, field in fields.items():
            setattr(self, name, field)

    @property
    def vertex_keys(self) -> Sequence[VertexKey]:
        return wrap(self._value.at("vertexKeys", encoded=False))

    @vertex_keys.setter
    def vertex_keys(self, value: Sequence[VertexKey]) -> None:
        self._value.set("vertexKeys", unwrap(value))

    @property
    def edge_keys(self) -> Sequence[EdgeKey]:
        return wrap(self._value.at("edgeKeys", encoded=False))

    @edge_keys.setter
    def edge_keys(self, value: Sequence[EdgeKey]) -> None:
        self._value.set("edgeKeys", unwrap(value))

    def __repr__(self) -> str:
        return f"Graph::GraphTopology(vertex_keys={self.vertex_keys}, edge_keys={self.edge_keys})"


class Position(Proxy):
    """Graph::Position.

    A Position.
    """

    __slots__ = ()

    @classmethod
    @functools.cache
    def type(cls) -> dsviper.TypeStructure:
        return definitions().check_structure(POSITION)

    @classmethod
    def decode(cls, blob, **kwargs) -> Position:
        """Relire depuis des octets : la classe connaît son type, donc elle peut le demander."""
        return cls(dsviper.ValueStructure.cast(
            dsviper.Value.decode(blob, cls.type(), definitions(), **kwargs)))

    def __init__(self, value: dsviper.ValueStructure | dict | None = None, /, **fields):
        if value is None:
            value = dsviper.ValueStructure(self.type())
        elif isinstance(value, dict):
            value = dsviper.ValueStructure(self.type(), value)
        elif value.type() != self.type():
            raise TypeError("cette valeur n'est pas un Graph::Position")
        super().__init__(value)

        for name, field in fields.items():
            setattr(self, name, field)

    @property
    def x(self) -> float:
        return self._value.at("x")

    @x.setter
    def x(self, value: float) -> None:
        self._value.set("x", value)

    @property
    def y(self) -> float:
        return self._value.at("y")

    @y.setter
    def y(self, value: float) -> None:
        self._value.set("y", value)

    def __repr__(self) -> str:
        return f"Graph::Position(x={self.x}, y={self.y})"


class Rectangle(Proxy):
    """Graph::Rectangle.

    A Rectangle.
    """

    __slots__ = ()

    @classmethod
    @functools.cache
    def type(cls) -> dsviper.TypeStructure:
        return definitions().check_structure(RECTANGLE)

    @classmethod
    def decode(cls, blob, **kwargs) -> Rectangle:
        """Relire depuis des octets : la classe connaît son type, donc elle peut le demander."""
        return cls(dsviper.ValueStructure.cast(
            dsviper.Value.decode(blob, cls.type(), definitions(), **kwargs)))

    def __init__(self, value: dsviper.ValueStructure | dict | None = None, /, **fields):
        if value is None:
            value = dsviper.ValueStructure(self.type())
        elif isinstance(value, dict):
            value = dsviper.ValueStructure(self.type(), value)
        elif value.type() != self.type():
            raise TypeError("cette valeur n'est pas un Graph::Rectangle")
        super().__init__(value)

        for name, field in fields.items():
            setattr(self, name, field)

    @property
    def x(self) -> float:
        """the x origin."""
        return self._value.at("x")

    @x.setter
    def x(self, value: float) -> None:
        self._value.set("x", value)

    @property
    def y(self) -> float:
        """the y origin."""
        return self._value.at("y")

    @y.setter
    def y(self, value: float) -> None:
        self._value.set("y", value)

    @property
    def w(self) -> float:
        """the width."""
        return self._value.at("w")

    @w.setter
    def w(self, value: float) -> None:
        self._value.set("w", value)

    @property
    def h(self) -> float:
        """the height."""
        return self._value.at("h")

    @h.setter
    def h(self, value: float) -> None:
        self._value.set("h", value)

    def __repr__(self) -> str:
        return f"Graph::Rectangle(x={self.x}, y={self.y}, w={self.w}, h={self.h})"


class VertexVisualAttributes(Proxy):
    """Graph::VertexVisualAttributes.

    The visual attributes of a vertex.
    """

    __slots__ = ()

    @classmethod
    @functools.cache
    def type(cls) -> dsviper.TypeStructure:
        return definitions().check_structure(VERTEX_VISUAL_ATTRIBUTES)

    @classmethod
    def decode(cls, blob, **kwargs) -> VertexVisualAttributes:
        """Relire depuis des octets : la classe connaît son type, donc elle peut le demander."""
        return cls(dsviper.ValueStructure.cast(
            dsviper.Value.decode(blob, cls.type(), definitions(), **kwargs)))

    def __init__(self, value: dsviper.ValueStructure | dict | None = None, /, **fields):
        if value is None:
            value = dsviper.ValueStructure(self.type())
        elif isinstance(value, dict):
            value = dsviper.ValueStructure(self.type(), value)
        elif value.type() != self.type():
            raise TypeError("cette valeur n'est pas un Graph::VertexVisualAttributes")
        super().__init__(value)

        for name, field in fields.items():
            setattr(self, name, field)

    @property
    def value(self) -> int:
        return self._value.at("value")

    @value.setter
    def value(self, value: int) -> None:
        self._value.set("value", value)

    @property
    def color(self) -> Color:
        return wrap(self._value.at("color", encoded=False))

    @color.setter
    def color(self, value: Color) -> None:
        self._value.set("color", unwrap(value))

    def __repr__(self) -> str:
        return f"Graph::VertexVisualAttributes(value={self.value}, color={self.color})"


class Vertex2DAttributes(Proxy):
    """Graph::Vertex2DAttributes.

    The attributes used to render a topological vertex in 2D.
    """

    __slots__ = ()

    @classmethod
    @functools.cache
    def type(cls) -> dsviper.TypeStructure:
        return definitions().check_structure(VERTEX_2D_ATTRIBUTES)

    @classmethod
    def decode(cls, blob, **kwargs) -> Vertex2DAttributes:
        """Relire depuis des octets : la classe connaît son type, donc elle peut le demander."""
        return cls(dsviper.ValueStructure.cast(
            dsviper.Value.decode(blob, cls.type(), definitions(), **kwargs)))

    def __init__(self, value: dsviper.ValueStructure | dict | None = None, /, **fields):
        if value is None:
            value = dsviper.ValueStructure(self.type())
        elif isinstance(value, dict):
            value = dsviper.ValueStructure(self.type(), value)
        elif value.type() != self.type():
            raise TypeError("cette valeur n'est pas un Graph::Vertex2DAttributes")
        super().__init__(value)

        for name, field in fields.items():
            setattr(self, name, field)

    @property
    def position(self) -> Position:
        return wrap(self._value.at("position", encoded=False))

    @position.setter
    def position(self, value: Position) -> None:
        self._value.set("position", unwrap(value))

    def __repr__(self) -> str:
        return f"Graph::Vertex2DAttributes(position={self.position})"


# Les classes de cette unité, par l'identifiant d'exécution de leur type : c'est ce qui
# permet à `wrap` de rendre un élément de conteneur avec son nom, sans qu'aucune classe de
# conteneur existe.
register({EDGE: EdgeKey, GRAPH: GraphKey, VERTEX: VertexKey, COLOR: Color, EDGE_TOPOLOGY: EdgeTopology, GRAPH_DESCRIPTION: GraphDescription, GRAPH_SELECTION: GraphSelection, GRAPH_TOPOLOGY: GraphTopology, POSITION: Position, RECTANGLE: Rectangle, VERTEX_2D_ATTRIBUTES: Vertex2DAttributes, VERTEX_VISUAL_ATTRIBUTES: VertexVisualAttributes})

__all__ = ["EdgeKey", "GraphKey", "VertexKey", "Color", "EdgeTopology", "GraphDescription", "GraphSelection", "GraphTopology", "Position", "Rectangle", "Vertex2DAttributes", "VertexVisualAttributes"]