# Generated by kibo from gei. Do not edit by hand.
# Templates: kibo-template-viper 2.0.0 (MIT), Template Model 2.
# Runtime: this file imports `dsviper` >=1.2.27 <1.3.0,
# distributed under LicenseRef-DigitalSubstrate-Commercial-1.2.
# Commercial use requires a Commercial Licence from Digital Substrate.
# Generated from /Volumes/DigitalSubstrate/kibo-2/dsviper-ge-qml/GE.dsm.json by kibo-2.0.0.jar


from __future__ import annotations

import base64
import functools
import zlib

import dsviper

from . import resources
from ._codegen import AnyConceptKey, AnyValue

__all__ = ["AnyConceptKey", "AnyValue", "definitions"]

@functools.cache
def definitions() -> dsviper.DefinitionsConst:
    blob = dsviper.ValueBlob(zlib.decompress(base64.b64decode(resources.B64_DEFINITIONS)))
    return dsviper.Definitions.decode(blob).const()


from . import containers  # noqa: E402