# Generated by kibo from gei. Do not edit by hand.
# Templates: kibo-template-viper 2.0.0 (MIT), Template Model 2.
# Runtime: this file imports `dsviper` >=1.2.27 <1.3.0,
# distributed under LicenseRef-DigitalSubstrate-Commercial-1.2.
# Commercial use requires a Commercial Licence from Digital Substrate.
# Generated from /Volumes/DigitalSubstrate/kibo-2/dsviper-ge-qml/GE.dsm.json by kibo-2.0.0.jar

from __future__ import annotations

import functools

import dsviper

from ._codegen import (mapping_of, optional_of, ordered_of, sequence_of,
                       variant_of)
from . import graph

type_bool = lambda: dsviper.TypeBool()
type_uint8 = lambda: dsviper.TypeUInt8()
type_uint16 = lambda: dsviper.TypeUInt16()
type_uint32 = lambda: dsviper.TypeUInt32()
type_uint64 = lambda: dsviper.TypeUInt64()
type_int8 = lambda: dsviper.TypeInt8()
type_int16 = lambda: dsviper.TypeInt16()
type_int32 = lambda: dsviper.TypeInt32()
type_int64 = lambda: dsviper.TypeInt64()
type_float = lambda: dsviper.TypeFloat()
type_double = lambda: dsviper.TypeDouble()
type_string = lambda: dsviper.TypeString()
type_blob = lambda: dsviper.TypeBlob()
type_blob_id = lambda: dsviper.TypeBlobId()
type_commit_id = lambda: dsviper.TypeCommitId()
type_uuid = lambda: dsviper.TypeUUId()
type_any = lambda: dsviper.TypeAny()
type_AnyConceptKey = lambda: dsviper.TypeKey(dsviper.TypeAnyConcept())
type_Graph_EdgeKey = graph.EdgeKey.type
type_Graph_GraphKey = graph.GraphKey.type
type_Graph_VertexKey = graph.VertexKey.type
type_Graph_Color = graph.Color.type
type_Graph_EdgeTopology = graph.EdgeTopology.type
type_Graph_GraphDescription = graph.GraphDescription.type
type_Graph_GraphSelection = graph.GraphSelection.type
type_Graph_GraphTopology = graph.GraphTopology.type
type_Graph_Position = graph.Position.type
type_Graph_Rectangle = graph.Rectangle.type
type_Graph_Vertex2DAttributes = graph.Vertex2DAttributes.type
type_Graph_VertexVisualAttributes = graph.VertexVisualAttributes.type

@functools.cache
def type_optional_AnyConceptKey(): return dsviper.TypeOptional(type_AnyConceptKey())
@functools.cache
def type_optional_xarray_string(): return dsviper.TypeOptional(type_xarray_string())
@functools.cache
def type_optional_Graph_EdgeKey(): return dsviper.TypeOptional(type_Graph_EdgeKey())
@functools.cache
def type_optional_Graph_EdgeTopology(): return dsviper.TypeOptional(type_Graph_EdgeTopology())
@functools.cache
def type_optional_Graph_GraphDescription(): return dsviper.TypeOptional(type_Graph_GraphDescription())
@functools.cache
def type_optional_Graph_GraphKey(): return dsviper.TypeOptional(type_Graph_GraphKey())
@functools.cache
def type_optional_Graph_GraphSelection(): return dsviper.TypeOptional(type_Graph_GraphSelection())
@functools.cache
def type_optional_Graph_GraphTopology(): return dsviper.TypeOptional(type_Graph_GraphTopology())
@functools.cache
def type_optional_Graph_Vertex2DAttributes(): return dsviper.TypeOptional(type_Graph_Vertex2DAttributes())
@functools.cache
def type_optional_Graph_VertexKey(): return dsviper.TypeOptional(type_Graph_VertexKey())
@functools.cache
def type_optional_Graph_VertexVisualAttributes(): return dsviper.TypeOptional(type_Graph_VertexVisualAttributes())
@functools.cache
def type_optional_map_string_to_string(): return dsviper.TypeOptional(type_map_string_to_string())
@functools.cache
def type_vector_string(): return dsviper.TypeVector(type_string())
@functools.cache
def type_set_Graph_EdgeKey(): return dsviper.TypeSet(type_Graph_EdgeKey())
@functools.cache
def type_set_Graph_GraphKey(): return dsviper.TypeSet(type_Graph_GraphKey())
@functools.cache
def type_set_Graph_VertexKey(): return dsviper.TypeSet(type_Graph_VertexKey())
@functools.cache
def type_set_string(): return dsviper.TypeSet(type_string())
@functools.cache
def type_map_string_to_string(): return dsviper.TypeMap(type_string(), type_string())
@functools.cache
def type_xarray_string(): return dsviper.TypeXArray(type_string())

Optional_AnyConceptKey = optional_of(type_optional_AnyConceptKey)
Optional_XArray_string = optional_of(type_optional_xarray_string)
Optional_Graph_EdgeKey = optional_of(type_optional_Graph_EdgeKey)
Optional_Graph_EdgeTopology = optional_of(type_optional_Graph_EdgeTopology)
Optional_Graph_GraphDescription = optional_of(type_optional_Graph_GraphDescription)
Optional_Graph_GraphKey = optional_of(type_optional_Graph_GraphKey)
Optional_Graph_GraphSelection = optional_of(type_optional_Graph_GraphSelection)
Optional_Graph_GraphTopology = optional_of(type_optional_Graph_GraphTopology)
Optional_Graph_Vertex2DAttributes = optional_of(type_optional_Graph_Vertex2DAttributes)
Optional_Graph_VertexKey = optional_of(type_optional_Graph_VertexKey)
Optional_Graph_VertexVisualAttributes = optional_of(type_optional_Graph_VertexVisualAttributes)
Optional_Map_string_to_string = optional_of(type_optional_map_string_to_string)
Vector_string = sequence_of(type_vector_string)
Set_Graph_EdgeKey = sequence_of(type_set_Graph_EdgeKey)
Set_Graph_GraphKey = sequence_of(type_set_Graph_GraphKey)
Set_Graph_VertexKey = sequence_of(type_set_Graph_VertexKey)
Set_string = sequence_of(type_set_string)
Map_string_to_string = mapping_of(type_map_string_to_string)
XArray_string = ordered_of(type_xarray_string)
